// ============================================================
//  EXTRA PRACTICE - difficulty levels, part 2 (new topics)
//  Each topic has id, title, icon and the three levels (15 words each).
//  w = words   [English, Slovenian, emoji (optional)]
//  s = gap sentences   [text with ___, answer, other accepted answers...]
// ============================================================
window.EXTRA_LEVELS = window.EXTRA_LEVELS || [];
window.EXTRA_LEVELS.push(
{ id: "body", title: "Body and health", icon: "🧍",
  easy: { w: [["head","glava","🧑"],["eye","oko","👁️"],["ear","uho","👂"],["nose","nos","👃"],["mouth","usta","👄"],["hand","roka","✋"],["foot","stopalo","🦶"],["leg","noga","🦵"],["arm","roka (od rame do dlani)","💪"],["finger","prst","☝️"],["hair","lasje"],["tooth","zob","🦷"],["back","hrbet"],["face","obraz"],["neck","vrat"]],
          s: [["We see with our ___.","eyes"],["We hear with our ___.","ears"],["We smell with our ___.","nose"],["I brush my ___ every morning and evening.","teeth"],["We have five ___ on each hand.","fingers"]] },
  medium: { w: [["shoulder","rama"],["elbow","komolec"],["knee","koleno"],["stomach","trebuh"],["chest","prsni koš"],["heart","srce","❤️"],["lungs","pljuča"],["skin","koža"],["toe","prst na nogi"],["thumb","palec"],["headache","glavobol","🤕"],["toothache","zobobol"],["cold","prehlad","🤧"],["temperature","vročina"],["medicine","zdravilo","💊"]],
            s: [["I bend my ___ to sit down.","knees","knee"],["I have a ___ ache, so I can't eat.","tooth"],["The ___ pumps blood round the body.","heart"],["I have a cold and a high ___.","temperature"],["I take ___ when I am ill.","medicine"]] },
  hard: { w: [["ankle","gleženj"],["wrist","zapestje"],["eyebrow","obrv"],["eyelash","trepalnica"],["forehead","čelo"],["chin","brada"],["cheek","lice"],["waist","pas, struk"],["muscle","mišica"],["bone","kost","🦴"],["brain","možgani","🧠"],["blood","kri","🩸"],["sprain","zvin"],["bruise","modrica"],["to cough","kašljati"]],
          s: [["You wear a watch on your ___.","wrist"],["I fell and now I have a blue ___ on my leg.","bruise"],["The ___ is inside your head and you think with it.","brain"],["I twisted my ___ when I was running.","ankle"],["If you are ill with a cold you often ___ and sneeze.","cough"]] } },

{ id: "house", title: "House and home", icon: "🏠",
  easy: { w: [["house","hiša","🏠"],["flat","stanovanje","🏢"],["room","soba"],["kitchen","kuhinja","🍳"],["bedroom","spalnica","🛏️"],["bathroom","kopalnica","🛁"],["living room","dnevna soba","🛋️"],["garden","vrt","🌷"],["door","vrata","🚪"],["window","okno","🪟"],["table","miza"],["bed","postelja"],["floor","tla"],["wall","stena"],["roof","streha"]],
          s: [["I sleep in my ___.","bedroom","bed"],["We cook in the ___.","kitchen"],["I take a shower in the ___.","bathroom"],["We watch TV in the ___ room.","living"],["Flowers grow in the ___.","garden"]] },
  medium: { w: [["sofa","kavč","🛋️"],["armchair","fotelj"],["wardrobe","omara"],["shelf","polica"],["carpet","preproga"],["curtains","zavese"],["lamp","svetilka","💡"],["mirror","ogledalo","🪞"],["cupboard","omarica"],["fridge","hladilnik"],["cooker","štedilnik"],["stairs","stopnice"],["balcony","balkon"],["attic","podstrešje"],["basement","klet"]],
            s: [["I keep my clothes in the ___.","wardrobe"],["We keep milk and cheese in the ___.","fridge"],["I look at myself in the ___.","mirror"],["We go up and down the ___.","stairs"],["Old things are in the ___ under the roof.","attic"]] },
  hard: { w: [["ceiling","strop"],["fireplace","kamin"],["chimney","dimnik"],["gate","vrata (na vrtu)"],["fence","ograja"],["drive","dovoz"],["terrace","terasa"],["landlord","gospodar najemnega stanovanja"],["rent","najemnina"],["to move in","vseliti se"],["to move out","izseliti se"],["furniture","pohištvo"],["detached","samostojna (hiša)"],["semi-detached","dvojček (hiša)"],["block of flats","blok"]],
          s: [["The lamp hangs from the ___.","ceiling"],["Smoke goes up the ___.","chimney"],["Tables and chairs are ___.","furniture"],["We pay ___ every month to live in this flat.","rent"],["They are leaving this house; next week they will ___ out.","move"]] } },

{ id: "transport", title: "Transport", icon: "🚌",
  easy: { w: [["car","avto","🚗"],["bus","avtobus","🚌"],["train","vlak","🚆"],["bike","kolo","🚲"],["plane","letalo","✈️"],["boat","čoln","⛵"],["ship","ladja","🚢"],["taxi","taksi","🚕"],["lorry","tovornjak","🚚"],["motorbike","motor","🏍️"],["tram","tramvaj","🚋"],["helicopter","helikopter","🚁"],["on foot","peš","🚶"],["road","cesta","🛣️"],["station","postaja"]],
          s: [["I go to school by ___ and I wait at the bus stop.","bus"],["A ___ flies in the sky.","plane","aeroplane","airplane"],["A ___ goes on rails.","train"],["I ride my ___ in the park.","bike","bicycle"],["A big ___ goes across the sea.","ship"]] },
  medium: { w: [["ticket","vozovnica","🎫"],["platform","peron"],["timetable","vozni red"],["passenger","potnik"],["driver","voznik"],["traffic","promet","🚦"],["traffic lights","semafor"],["pavement","pločnik"],["zebra crossing","prehod za pešce"],["petrol","bencin","⛽"],["airport","letališče"],["underground","podzemna železnica"],["motorway","avtocesta"],["journey","potovanje"],["late","zamudil"]],
            s: [["You buy a ___ before you get on a train.","ticket"],["We cross the road at the zebra ___.","crossing"],["Cars stop at red ___.","lights","traffic lights"],["The train leaves from ___ 3.","platform"],["There is a lot of ___ in the city at 8 o'clock.","traffic"]] },
  hard: { w: [["to board","vkrcati se"],["to get off","izstopiti"],["to commute","vsakodnevno se voziti v službo"],["to park","parkirati"],["roundabout","krožišče"],["junction","križišče"],["speed limit","omejitev hitrosti"],["seat belt","varnostni pas"],["helmet","čelada","⛑️"],["fare","cena vozovnice"],["delay","zamuda"],["luggage","prtljaga","🧳"],["pedestrian","pešec"],["to overtake","prehiteti"],["traffic jam","prometni zastoj"]],
          s: [["You must wear a ___ when you ride a motorbike.","helmet"],["The train was late because of a long ___.","delay"],["We were stuck in a traffic ___ for an hour.","jam"],["Always fasten your ___ belt in a car.","seat"],["A ___ is a person who walks along the street.","pedestrian"]] } },

{ id: "sports", title: "Sports", icon: "⚽",
  easy: { w: [["basketball","košarka","🏀"],["tennis","tenis","🎾"],["volleyball","odbojka","🏐"],["handball","rokomet","🤾"],["athletics","atletika","🏃"],["skiing","smučanje","⛷️"],["swimming","plavanje","🏊"],["match","tekma"],["team","ekipa"],["ball","žoga","⚽"],["player","igralec"],["goal","gol"],["race","tekma v teku"],["win","zmagati"],["lose","izgubiti"]],
          s: [["You score a ___ in football.","goal"],["In ___ you throw the ball into a basket.","basketball"],["Eleven players are in a football ___.","team"],["The winner is the first to cross the line in a ___.","race"],["If you don't win, you ___.","lose"]] },
  medium: { w: [["referee","sodnik","🧑‍⚖️"],["coach","trener"],["fan","navijač"],["stadium","stadion","🏟️"],["score","rezultat"],["champion","prvak","🏆"],["medal","medalja","🏅"],["training","trening"],["pitch","igrišče"],["court","igrišče (tenis...)"],["net","mreža"],["racket","lopar"],["helmet","čelada"],["to kick","brcniti"],["to throw","vreči"]],
            s: [["The ___ blows the whistle.","referee"],["We play tennis on a ___.","court"],["Players practise at ___ twice a week.","training"],["The final ___ was 2–1.","score"],["The winner receives a gold ___.","medal"]] },
  hard: { w: [["tournament","turnir"],["championship","prvenstvo"],["opponent","nasprotnik"],["defender","branilec"],["goalkeeper","vratar"],["striker","napadalec"],["penalty","enajstmetrovka"],["draw","neodločeno"],["to beat","premagati"],["to compete","tekmovati"],["to qualify","uvrstiti se"],["injury","poškodba"],["warm-up","ogrevanje"],["extra time","podaljšek"],["to cheer","navijati"]],
          s: [["The ___ stops the ball in front of the goal.","goalkeeper","keeper"],["The match ended in a ___: 1–1.","draw"],["Our team will ___ the other team if we play well.","beat"],["Before a match the players do a ___.","warm-up"],["Fans ___ for their team.","cheer"]] } },

{ id: "town", title: "Town and places", icon: "🏙️",
  easy: { w: [["town","mesto, kraj"],["city","mesto","🏙️"],["village","vas","🏘️"],["street","ulica"],["shop","trgovina","🏪"],["school","šola","🏫"],["hospital","bolnišnica","🏥"],["park","park","🌳"],["post office","pošta","📮"],["bank","banka","🏦"],["church","cerkev","⛪"],["cinema","kino","🎬"],["museum","muzej"],["supermarket","supermarket","🛒"],["bridge","most","🌉"]],
          s: [["We watch films at the ___.","cinema"],["You can buy bread at the ___.","bakery","shop","supermarket"],["Sick people go to the ___.","hospital"],["I keep my money in the ___.","bank"],["We play in the ___ after school.","park"]] },
  medium: { w: [["library","knjižnica"],["pharmacy","lekarna","💊"],["restaurant","restavracija","🍽️"],["café","kavarna","☕"],["market","tržnica"],["bus stop","avtobusna postaja"],["fire station","gasilski dom"],["police station","policijska postaja"],["town hall","mestna hiša"],["shopping centre","nakupovalno središče"],["car park","parkirišče"],["swimming pool","bazen"],["zoo","živalski vrt","🦁"],["crossroads","križišče"],["corner","vogal"]],
            s: [["You buy medicine at the ___.","pharmacy","chemist"],["We eat lunch at a ___.","restaurant"],["You leave your car in the ___ park.","car"],["Turn left at the ___.","corner","crossroads"],["We saw lions and elephants at the ___.","zoo"]] },
  hard: { w: [["suburb","predmestje"],["neighbourhood","soseska"],["skyscraper","nebotičnik"],["factory","tovarna","🏭"],["monument","spomenik"],["fountain","vodnjak","⛲"],["square","trg"],["pedestrian zone","peš cona"],["cathedral","katedrala"],["castle","grad","🏰"],["opposite","nasproti"],["next to","poleg"],["between","med"],["across from","nasproti"],["behind","za"]],
          s: [["A very tall building with many floors is a ___.","skyscraper"],["The bank is ___ the post office: they are on the same side, side by side.","next to","beside"],["Car-free streets form a ___ zone.","pedestrian"],["The old ___ stands on a hill.","castle"],["There is a ___ in the middle of the square with water coming out.","fountain"]] } },

{ id: "feelings", title: "Feelings and character", icon: "😊",
  easy: { w: [["happy","vesel","😀"],["sad","žalosten","😢"],["angry","jezen","😠"],["tired","utrujen","😴"],["hungry","lačen"],["thirsty","žejen"],["scared","prestrašen","😨"],["excited","navdušen","🤩"],["bored","naveličan","🥱"],["nervous","živčen"],["surprised","presenečen","😮"],["kind","prijazen"],["funny","smešen","😄"],["shy","sramežljiv"],["friendly","prijazen, družaben"]],
          s: [["I am ___ because I have not eaten since morning.","hungry"],["He is ___ because he lost his toy.","sad"],["I'm very ___; I want to go to bed.","tired"],["The film was so boring that I was ___.","bored"],["She is ___ about the school trip: she can't wait.","excited"]] },
  medium: { w: [["proud","ponosen"],["jealous","ljubosumen"],["lonely","osamljen"],["worried","zaskrbljen"],["embarrassed","v zadregi"],["disappointed","razočaran"],["relieved","olajšan"],["confident","samozavesten"],["polite","vljuden"],["rude","nesramen"],["lazy","len"],["clever","pameten"],["brave","pogumen"],["honest","pošten"],["generous","radodaren"]],
            s: [["She is a ___ girl: she helps everyone and shares her things.","generous","kind"],["He told the truth: he is an ___ boy.","honest"],["He never says please or thank you. He is ___.","rude","impolite"],["I am ___ of my sister because she won the competition.","proud"],["The firefighter was very ___: he went into the fire.","brave"]] },
  hard: { w: [["grateful","hvaležen"],["ashamed","osramočen"],["furious","besen"],["delighted","navdušen, zelo vesel"],["anxious","zaskrbljen, tesnoben"],["curious","radoveden"],["stubborn","trmast"],["moody","muhast"],["selfish","sebičen"],["reliable","zanesljiv"],["sensitive","občutljiv"],["cheerful","vedre volje"],["bossy","avtoritaren"],["to be fed up","biti sit"],["to cheer up","razvedriti se"]],
          s: [["You can always count on her; she is very ___.","reliable"],["She only thinks of herself: she is ___.","selfish"],["He does not change his mind even if he is wrong: he is ___.","stubborn"],["I'm so ___ for your help. Thank you!","grateful"],["Cheer ___! Things will get better.","up"]] } },

{ id: "calendar", title: "Time and calendar", icon: "📅",
  easy: { w: [["Monday","ponedeljek"],["Tuesday","torek"],["Wednesday","sreda"],["Thursday","četrtek"],["Friday","petek"],["Saturday","sobota"],["Sunday","nedelja"],["January","januar"],["February","februar"],["March","marec"],["April","april"],["May","maj"],["June","junij"],["July","julij"],["August","avgust"]],
          s: [["The first day of the school week is ___.","Monday"],["The day after Friday is ___.","Saturday"],["The last day of the week is ___.","Sunday"],["The first month of the year is ___.","January"],["Christmas is in ___.","December"]] },
  medium: { w: [["September","september"],["October","oktober"],["November","november"],["December","december"],["morning","jutro"],["afternoon","popoldne"],["evening","večer"],["night","noč"],["yesterday","včeraj"],["today","danes"],["tomorrow","jutri"],["week","teden"],["weekend","vikend"],["birthday","rojstni dan","🎂"],["holiday","počitnice, praznik"]],
            s: [["Today is Tuesday, so ___ is Wednesday.","tomorrow"],["Saturday and Sunday are the ___.","weekend"],["Yesterday was Monday, so today is ___.","Tuesday"],["Seven days make one ___.","week"],["I usually have breakfast in the ___.","morning"]] },
  hard: { w: [["fortnight","dva tedna"],["decade","desetletje"],["century","stoletje"],["leap year","prestopno leto"],["season","letni čas"],["midnight","polnoč"],["noon","poldne"],["dawn","zora"],["dusk","mrak"],["daily","dnevno"],["weekly","tedensko"],["monthly","mesečno"],["annual","letni"],["occasionally","občasno"],["nowadays","dandanes"]],
          s: [["Twelve o'clock at night is ___.","midnight"],["A hundred years make a ___.","century"],["Ten years make a ___.","decade"],["Two weeks make a ___.","fortnight"],["A magazine that comes out every week is a ___ magazine.","weekly"]] } },

{ id: "nature", title: "Nature and environment", icon: "🌳",
  easy: { w: [["tree","drevo","🌳"],["flower","cvet","🌸"],["grass","trava"],["river","reka"],["lake","jezero"],["sea","morje","🌊"],["mountain","gora","⛰️"],["forest","gozd","🌲"],["beach","plaža","🏖️"],["sky","nebo"],["star","zvezda","⭐"],["moon","luna","🌙"],["sun","sonce","☀️"],["hill","hrib"],["island","otok","🏝️"]],
          s: [["The ___ is full of tall trees.","forest","wood"],["Fish live in the ___.","river","lake","sea"],["We swim in the sea and play on the ___.","beach"],["At night we can see the ___ and the stars.","moon"],["Snow lies on the top of the ___.","mountain"]] },
  medium: { w: [["leaf","list","🍃"],["branch","veja"],["root","korenina"],["field","polje"],["valley","dolina"],["waterfall","slap"],["cave","jama"],["desert","puščava","🏜️"],["rainforest","deževni gozd"],["pond","ribnik"],["stream","potok"],["rock","skala"],["sand","pesek"],["soil","prst"],["planet","planet","🪐"]],
            s: [["Plants take water from the ___ with their roots.","soil","ground"],["Water falls from a high rock in a ___.","waterfall"],["A ___ is a very dry place with a lot of sand.","desert"],["A tree has a trunk, ___ and leaves.","branches","roots"],["The Earth is a ___.","planet"]] },
  hard: { w: [["environment","okolje"],["pollution","onesnaževanje"],["recycling","recikliranje","♻️"],["litter","smeti"],["rubbish","odpadki"],["endangered","ogrožen"],["extinct","izumrl"],["climate change","podnebne spremembe"],["global warming","globalno segrevanje"],["renewable","obnovljiv"],["solar panel","sončna celica"],["wind farm","vetrna elektrarna"],["to protect","varovati"],["to waste","zapravljati"],["to save energy","varčevati z energijo"]],
          s: [["Dirty air and water are called ___.","pollution"],["Dinosaurs are ___: they no longer exist.","extinct"],["Putting paper and glass in different bins is called ___.","recycling"],["We must ___ nature.","protect"],["Throwing ___ on the ground is bad for the environment.","litter","rubbish"]] } },

{ id: "technology", title: "Technology and media", icon: "💻",
  easy: { w: [["phone","telefon","📱"],["computer","računalnik","💻"],["laptop","prenosnik"],["tablet","tablični računalnik"],["TV","televizija","📺"],["camera","fotoaparat","📷"],["headphones","slušalke","🎧"],["screen","zaslon"],["keyboard","tipkovnica","⌨️"],["mouse","miška","🖱️"],["game","igra","🎮"],["video","video"],["photo","fotografija"],["music","glasba","🎵"],["radio","radio","📻"]],
          s: [["I type on the ___.","keyboard"],["I listen to music with ___.","headphones"],["I take a ___ with my camera.","photo","picture"],["We watch cartoons on ___.","TV","television"],["I send messages from my ___.","phone","mobile","mobile phone"]] },
  medium: { w: [["internet","internet"],["website","spletna stran"],["email","e-pošta","📧"],["password","geslo","🔑"],["app","aplikacija"],["download","prenesti"],["upload","naložiti"],["search","iskati"],["online","na spletu"],["message","sporočilo"],["social media","družabna omrežja"],["charger","polnilec","🔌"],["battery","baterija","🔋"],["wifi","brezžično omrežje"],["file","datoteka"]],
            s: [["I need a ___ to log in to my account.","password"],["My phone is dead: I need to plug in the ___.","charger"],["I ___ games from the internet to my phone.","download","downloaded"],["You look for information on a ___.","website","web page"],["My phone has no ___, so it won't turn on.","battery","power"]] },
  hard: { w: [["software","programska oprema"],["hardware","strojna oprema"],["to log in","prijaviti se"],["to log out","odjaviti se"],["to update","posodobiti"],["to install","namestiti"],["to delete","izbrisati"],["to share","deliti"],["to scroll","drseti po strani"],["to stream","pretakati"],["to be addicted to","biti odvisen od"],["privacy","zasebnost"],["cyberbullying","spletno nasilje"],["artificial intelligence","umetna inteligenca"],["virus","virus"]],
          s: [["You ___ in with your name and password.","log"],["Don't post personal information online, protect your ___.","privacy"],["I ___ my favourite series on my laptop.","stream","watch"],["Making fun of someone online is called ___.","cyberbullying","bullying"],["I need to ___ the app to the newest version.","update"]] } },

{ id: "travel", title: "Travel and holidays", icon: "🧳",
  easy: { w: [["holiday","počitnice"],["hotel","hotel","🏨"],["tent","šotor","⛺"],["suitcase","kovček","🧳"],["map","zemljevid","🗺️"],["passport","potni list"],["ticket","vstopnica, vozovnica"],["beach","plaža"],["sea","morje"],["mountains","gore"],["camping","kampiranje"],["tourist","turist"],["trip","izlet"],["souvenir","spominek"],["postcard","razglednica"]],
          s: [["We sleep in a ___ when we go camping.","tent"],["I put my clothes in a ___.","suitcase"],["I send a ___ to my grandma.","postcard"],["I look at a ___ so I don't get lost.","map"],["We stay in a ___ in the city.","hotel"]] },
  medium: { w: [["abroad","v tujini"],["foreign","tuj"],["guide","vodnik"],["sightseeing","ogled znamenitosti"],["luggage","prtljaga"],["customs","carina"],["currency","valuta"],["exchange","menjati"],["reservation","rezervacija"],["to book","rezervirati"],["to pack","pakirati"],["to unpack","razpakirati"],["to get lost","izgubiti se"],["destination","cilj potovanja"],["journey","potovanje"]],
            s: [["We went ___ and visited Italy and Austria.","abroad"],["Before the trip I ___ my bag.","pack","packed"],["We ___ a room in the hotel online.","booked","book"],["The ___ showed us around the old town.","guide"],["The euro is the ___ of Slovenia.","currency"]] },
  hard: { w: [["itinerary","potovalni načrt"],["accommodation","namestitev"],["package holiday","aranžma"],["backpacker","popotnik z nahrbtnikom"],["resort","letovišče"],["jet lag","utrujenost po dolgem letu"],["visa","vizum"],["boarding card","vstopna karta"],["departure","odhod"],["arrival","prihod"],["delayed","zamujen"],["cancelled","odpovedan"],["to check in","prijaviti se"],["to check out","odjaviti se"],["to set off","odpraviti se"]],
          s: [["Planes leave from the ___ gate.","departure"],["At the airport you ___ in before the flight.","check"],["The flight was ___ because of the storm, so we didn't fly.","cancelled","canceled"],["You need a ___ to enter some countries.","visa"],["We ___ off early in the morning.","set"]] } },

{ id: "shopping", title: "Shopping and money", icon: "🛒",
  easy: { w: [["shop","trgovina"],["money","denar","💰"],["price","cena"],["cheap","poceni"],["expensive","drag"],["to buy","kupiti"],["to sell","prodati"],["to pay","plačati"],["change","drobiž"],["coin","kovanec","🪙"],["note","bankovec"],["basket","košara","🧺"],["bag","vrečka"],["customer","stranka"],["receipt","račun"]],
          s: [["I ___ a new T-shirt in the shop.","bought","buy"],["This coat is very ___: it costs 300 euros.","expensive"],["You can find the ___ on the label.","price"],["I paid with a 10 euro ___ and got some change.","note"],["The ___ is the person who buys things.","customer"]] },
  medium: { w: [["bargain","dobra kupčija"],["sale","razprodaja"],["discount","popust"],["offer","ponudba"],["credit card","kreditna kartica","💳"],["cash","gotovina"],["cashier","blagajnik"],["checkout","blagajna"],["trolley","voziček"],["queue","vrsta"],["shopping list","nakupovalni seznam"],["pocket money","žepnina"],["to cost","stati"],["to spend","porabiti"],["to save","varčevati"]],
          s: [["I get ten euros of ___ money every week.","pocket"],["I pay at the ___.","checkout","till"],["It was on ___, so it was half price.","sale"],["Don't ___ all your money on sweets!","spend"],["How much does this T-shirt ___?","cost"]] },
  hard: { w: [["to afford","privoščiti si"],["to owe","dolgovati"],["to refund","vrniti denar"],["to bargain","barantati"],["to browse","brskati"],["to exchange","zamenjati"],["warranty","garancija"],["wallet","denarnica"],["purse","denarnica (ženska)"],["bill","račun (v restavraciji)"],["tip","napitnina"],["income","dohodek"],["debt","dolg"],["loan","posojilo"],["bargain hunter","lovec na popuste"]],
          s: [["I can't ___ a new phone; it's too expensive.","afford"],["If you don't like it, you can get a ___.","refund"],["We left a ___ for the waiter.","tip"],["In the market you can ___ to get a lower price.","bargain"],["If something breaks in the first year, the ___ covers it.","warranty","guarantee"]] } },

{ id: "verbs", title: "Irregular verbs", icon: "🔤",
  easy: { w: [["go – went","iti – šel"],["see – saw","videti – videl"],["eat – ate","jesti – jedel"],["drink – drank","piti – pil"],["have – had","imeti – imel"],["make – made","narediti – naredil"],["take – took","vzeti – vzel"],["come – came","priti – prišel"],["give – gave","dati – dal"],["get – got","dobiti – dobil"],["buy – bought","kupiti – kupil"],["write – wrote","pisati – pisal"],["read – read","brati – bral"],["run – ran","teči – tekel"],["swim – swam","plavati – plaval"]],
          s: [["Yesterday I ___ (go) to the cinema.","went"],["She ___ (eat) an apple at lunch.","ate"],["We ___ (see) a film last night.","saw"],["He ___ (have) a shower this morning.","had"],["I ___ (buy) a new bag on Saturday.","bought"]] },
  medium: { w: [["know – knew","vedeti – vedel"],["think – thought","misliti – mislil"],["say – said","reči – rekel"],["tell – told","povedati – povedal"],["find – found","najti – našel"],["leave – left","oditi – odšel"],["meet – met","srečati – srečal"],["sit – sat","sedeti – sedel"],["stand – stood","stati – stal"],["sleep – slept","spati – spal"],["speak – spoke","govoriti – govoril"],["sing – sang","peti – pel"],["fly – flew","leteti – letel"],["drive – drove","voziti – vozil"],["wear – wore","nositi – nosil"]],
            s: [["I ___ (sleep) badly last night.","slept"],["They ___ (meet) at the station.","met"],["She ___ (sing) a beautiful song.","sang"],["We ___ (fly) to Spain last summer.","flew"],["He ___ (wear) a blue jacket yesterday.","wore"]] },
  hard: { w: [["begin – began – begun","začeti"],["break – broke – broken","zlomiti"],["choose – chose – chosen","izbrati"],["forget – forgot – forgotten","pozabiti"],["lend – lent – lent","posoditi"],["lose – lost – lost","izgubiti"],["steal – stole – stolen","ukrasti"],["throw – threw – thrown","vreči"],["wake – woke – woken","zbuditi se"],["win – won – won","zmagati"],["hide – hid – hidden","skriti"],["bite – bit – bitten","ugrizniti"],["shake – shook – shaken","tresti"],["bring – brought – brought","prinesti"],["teach – taught – taught","učiti"]],
          s: [["I have ___ (lose) my keys!","lost"],["She has already ___ (break) her phone.","broken"],["Our team ___ (win) the match last week.","won"],["He has ___ (forget) his homework again.","forgotten"],["Who ___ (teach) you to swim?","taught"]] } }
);
