// ============================================================
//  EXTRA PRACTICE - difficulty levels, part 1 (the nine original topics)
//  Same ids as in sets.js: the words in sets.js are the first words of "Easy";
//  this file adds more easy words and the Medium and Hard levels.
//  w = words   [English, Slovenian, emoji (optional)]
//  s = gap sentences   [text with ___, answer, other accepted answers...]
// ============================================================
window.EXTRA_LEVELS = window.EXTRA_LEVELS || [];
window.EXTRA_LEVELS.push(
{ id: "colours",
  easy: { w: [["grey","siva","🐘"],["gold","zlata","🥇"],["silver","srebrna","🥈"],["dark blue","temno modra","🌌"],["light green","svetlo zelena","🍏"]],
          s: [["Elephants are ___.","grey"],["The winner gets a ___ medal.","gold"],["The second prize is a ___ medal.","silver"],["Mix yellow and blue and you get ___.","green"],["Mix red and yellow and you get ___.","orange"]] },
  medium: { w: [["turquoise","turkizna","🏝️"],["beige","bež"],["cream","kremna","🍦"],["violet","vijoličasta","🪻"],["lime green","limetno zelena","🍋"],["sky blue","nebesno modra","🌤️"],["dark","temen","🌑"],["light","svetel","💡"],["pale","bled"],["bright","živ, svetel","🌟"],["striped","progast","🦓"],["spotted","pikast","🐆"],["colourful","pisan","🌈"],["navy","mornarsko modra","⚓"],["khaki","kaki"]],
            s: [["A zebra has ___ skin: black and white lines.","striped"],["A leopard is yellow with black ___ skin.","spotted"],["A rainbow is very ___.","colourful"],["The sea near a tropical island is often ___.","turquoise"],["Dark red is the opposite of ___ red.","light","pale","bright"]] },
  hard: { w: [["scarlet","škrlatna"],["crimson","temno rdeča"],["indigo","indigo"],["lavender","sivkina barva","💜"],["amber","jantarna"],["ivory","slonokoščena"],["charcoal","črnosiva"],["olive","olivna","🫒"],["mustard","gorčična"],["magenta","magenta"],["emerald","smaragdno zelena","💚"],["teal","modrozelena"],["transparent","prozoren","🪟"],["shade","odtenek"],["faded","zbledel"]],
          s: [["A glass window is ___: you can see through it.","transparent"],["This is a lovely ___ of blue, a bit darker than the sky.","shade"],["My old jeans are ___ because I have washed them so many times.","faded"],["A bright green stone, like in a royal ring, is an ___.","emerald"],["Pickled green fruit that grows on a tree in Italy and Greece is called an ___.","olive"]] } },

{ id: "school",
  easy: { w: [["teacher","učitelj/učiteljica","🧑‍🏫"],["desk","miza","🪑"],["chair","stol","💺"],["bag","torba","👜"],["rubber","radirka"]],
          s: [["You write in your ___.","notebook","exercise book"],["I sit at my ___ in the classroom.","desk"],["I use a ___ to rub out a mistake.","rubber","eraser"],["The ___ teaches us English.","teacher"],["I carry my books in my ___.","bag","backpack","schoolbag"]] },
  medium: { w: [["glue","lepilo","🧴"],["marker","flomaster","🖍️"],["highlighter","označevalec"],["sharpener","šilček"],["pencil case","peresnica"],["whiteboard","bela tabla"],["projector","projektor","📽️"],["dictionary","slovar","📖"],["timetable","urnik","🗓️"],["homework","domača naloga"],["break","odmor"],["canteen","jedilnica"],["library","knjižnica","📚"],["gym","telovadnica","🏋️"],["playground","igrišče"]],
            s: [["I look up new words in a ___.","dictionary"],["My ___ shows which lessons I have on Monday.","timetable"],["We have lunch in the school ___.","canteen"],["We borrow books from the school ___.","library"],["In the ___ we play basketball and volleyball.","gym","sports hall"]] },
  hard: { w: [["stapler","spenjalnik"],["compass","šestilo"],["protractor","kotomer","📐"],["glue stick","lepilo v stiku"],["worksheet","delovni list"],["textbook","učbenik"],["register","dnevnik"],["detention","kazen po pouku"],["term","trimesečje, semester"],["certificate","spričevalo"],["assembly","šolska prireditev, zbor"],["locker","omarica"],["tutor","razrednik, mentor"],["recess","odmor (US)"],["staff room","zbornica"]],
          s: [["You use a ___ to measure an angle.","protractor"],["The teachers have their coffee in the ___ room.","staff"],["At the end of the school year you get a ___.","certificate","report card"],["The teacher gave us a ___ with ten questions to fill in.","worksheet"],["I keep my coat and books in my ___.","locker"]] } },

{ id: "animals",
  easy: { w: [["duck","raca","🦆"],["frog","žaba","🐸"],["lion","lev","🦁"],["elephant","slon","🐘"],["monkey","opica","🐒"]],
          s: [["A ___ says quack.","duck"],["The ___ is the king of the animals.","lion"],["A ___ has a very long nose called a trunk.","elephant"],["A ___ jumps and lives near water.","frog"],["A ___ eats bananas and climbs trees.","monkey"]] },
  medium: { w: [["giraffe","žirafa","🦒"],["zebra","zebra","🦓"],["tiger","tiger","🐅"],["bear","medved","🐻"],["wolf","volk","🐺"],["fox","lisica","🦊"],["squirrel","veverica","🐿️"],["snake","kača","🐍"],["turtle","želva","🐢"],["dolphin","delfin","🐬"],["shark","morski pes","🦈"],["whale","kit","🐋"],["hedgehog","jež","🦔"],["owl","sova","🦉"],["butterfly","metulj","🦋"]],
            s: [["A ___ has the longest neck of all animals.","giraffe"],["A ___ has black and white stripes.","zebra"],["A ___ carries its house on its back.","turtle","tortoise"],["A ___ is a big fish with sharp teeth.","shark"],["An ___ can see well at night and says hoo-hoo.","owl"]] },
  hard: { w: [["kangaroo","kenguru","🦘"],["crocodile","krokodil","🐊"],["penguin","pingvin","🐧"],["hippo","povodni konj","🦛"],["rhino","nosorog","🦏"],["cheetah","gepard","🐆"],["gorilla","gorila","🦍"],["peacock","pav","🦚"],["bat","netopir","🦇"],["octopus","hobotnica","🐙"],["jellyfish","meduza"],["lizard","kuščar","🦎"],["beaver","bober"],["otter","vidra","🦦"],["camel","kamela","🐫"]],
          s: [["A ___ has a baby in a pocket on its tummy.","kangaroo"],["The ___ is the fastest animal on land.","cheetah"],["A ___ is a bird that cannot fly and lives in the cold south.","penguin"],["An ___ has eight arms.","octopus"],["A ___ has one or two humps and lives in the desert.","camel"]] } },

{ id: "family",
  easy: { w: [["parents","starši","👨‍👩‍👧"],["children","otroci","🧒"],["son","sin","👦"],["daughter","hči","👧"],["grandparents","stari starši","👵"]],
          s: [["My mother's mother is my ___.","grandmother","grandma"],["My father and mother are my ___.","parents"],["My uncle's son is my ___.","cousin"],["I am their ___: they have a daughter and a son.","child"],["My brother is my parents' ___.","son"]] },
  medium: { w: [["nephew","nečak"],["niece","nečakinja"],["husband","mož"],["wife","žena"],["twin","dvojček","👯"],["grandson","vnuk"],["granddaughter","vnukinja"],["relatives","sorodniki"],["only child","edinec"],["neighbour","sosed"],["friend","prijatelj","🧑‍🤝‍🧑"],["pet","hišni ljubljenček","🐕"],["stepmother","mačeha"],["stepfather","očim"],["family tree","družinsko drevo","🌳"]],
            s: [["My sister's son is my ___.","nephew"],["My sister's daughter is my ___.","niece"],["I have no brothers or sisters. I am an ___ child.","only"],["My mum's husband is my ___.","dad","father","stepfather","stepdad"],["The people who live next door are our ___.","neighbours"]] },
  hard: { w: [["siblings","bratje in sestre"],["in-laws","tast/tašča, svak ..."],["mother-in-law","tašča"],["father-in-law","tast"],["ancestor","prednik"],["generation","generacija"],["half-brother","polbrat"],["godmother","botra"],["orphan","sirota"],["to look after","skrbeti za"],["to bring up","vzgajati"],["to take after","biti podoben"],["to get on with","razumeti se z"],["relative","sorodnik"],["adopted","posvojen"]],
          s: [["Brothers and sisters are called ___.","siblings"],["I look like my father: I ___ after him.","take"],["Her parents ___ her up very well.","brought"],["I really ___ on with my cousin; we never argue.","get"],["My wife's mother is my ___.","mother-in-law"]] } },

{ id: "food",
  easy: { w: [["butter","maslo","🧈"],["soup","juha","🍲"],["tea","čaj","🍵"],["juice","sok","🧃"],["sandwich","sendvič","🥪"]],
          s: [["I put ___ on my bread.","butter"],["I drink hot ___ with lemon.","tea"],["A ___ is two slices of bread with cheese or ham.","sandwich"],["Orange ___ is a healthy drink.","juice"],["We eat ___ with a spoon.","soup"]] },
  medium: { w: [["vegetables","zelenjava","🥦"],["fruit","sadje","🍓"],["potato","krompir","🥔"],["carrot","korenje","🥕"],["tomato","paradižnik","🍅"],["onion","čebula","🧅"],["cucumber","kumara","🥒"],["strawberry","jagoda","🍓"],["cake","torta","🍰"],["biscuit","piškot","🍪"],["sausage","klobasa","🌭"],["pasta","testenine","🍝"],["honey","med","🍯"],["yoghurt","jogurt"],["breakfast","zajtrk","🍳"]],
            s: [["The first meal of the day is ___.","breakfast"],["Bees make ___.","honey"],["Spaghetti is a kind of ___.","pasta"],["Chips are made from ___.","potatoes","potato"],["Rabbits love to eat ___.","carrots","carrot"]] },
  hard: { w: [["ingredient","sestavina"],["recipe","recept"],["flour","moka"],["sugar","sladkor"],["spicy","pekoč, začinjen","🌶️"],["sour","kisel","🍋"],["sweet","sladek"],["bitter","grenak"],["salty","slan"],["raw","surov"],["delicious","okusen"],["leftovers","ostanki hrane"],["vegetarian","vegetarijanec"],["allergic","alergičen"],["to chop","sesekljati"]],
          s: [["To bake a cake you need eggs, ___ and sugar.","flour"],["A ___ tells you how to cook a dish.","recipe"],["Lemons are very ___.","sour"],["Chilli peppers are very ___.","spicy","hot"],["A ___ does not eat meat or fish.","vegetarian"]] } },

{ id: "clothes",
  easy: { w: [["T-shirt","majica","👕"],["jeans","kavbojke","👖"],["coat","plašč","🧥"],["boots","škornji","🥾"],["cap","kapa s ščitnikom","🧢"]],
          s: [["I wear ___ on my feet before my shoes.","socks"],["In winter I wear a warm ___.","coat","jacket"],["I wear a ___ on my head.","hat","cap"],["Many people wear blue ___ on weekends.","jeans"],["We wear ___ when it rains and the ground is wet.","boots","wellies"]] },
  medium: { w: [["jumper","pulover"],["sweatshirt","pulover s kapuco"],["pyjamas","pižama","🛌"],["swimsuit","kopalke","👙"],["tracksuit","trenirka"],["trainers","tekaški copati","👟"],["sandals","sandali","🩴"],["belt","pas"],["tie","kravata","👔"],["umbrella","dežnik","☂️"],["uniform","uniforma"],["to wear","nositi"],["to put on","obleči"],["to take off","sleči"],["pocket","žep"]],
            s: [["I wear my ___ in bed at night.","pyjamas"],["It's raining, so take your ___.","umbrella"],["Before bed I ___ off my clothes.","take"],["Children in some schools wear a ___.","uniform"],["I keep my phone in my ___.","pocket"]] },
  hard: { w: [["cardigan","jopica na zapenjanje"],["raincoat","dežni plašč"],["waistcoat","telovnik"],["tights","hlačne nogavice"],["bracelet","zapestnica"],["necklace","ogrlica"],["earrings","uhani"],["glasses","očala","👓"],["sunglasses","sončna očala","🕶️"],["fashionable","modern"],["loose","ohlapen"],["tight","tesen"],["to fit","ustrezati po velikosti"],["to suit","pristajati"],["second-hand","rabljen"]],
          s: [["These shoes are too small; they don't ___ me.","fit"],["This colour really ___ you.","suits"],["The trousers are too big and ___ on me.","loose"],["I bought this jacket in a ___ shop, so it was cheap.","second-hand"],["She wears a gold ___ around her neck.","necklace","chain"]] } },

{ id: "weather",
  easy: { w: [["sun","sonce","☀️"],["rain","dež","🌧️"],["snow","sneg","❄️"],["wind","veter","💨"],["cloud","oblak","☁️"]],
          s: [["The ___ shines in the sky on a sunny day.","sun"],["We build a snowman when there is lots of ___.","snow"],["Wet weather is ___.","rainy"],["Today is very ___; my kite is flying.","windy"],["When it's ___, I wear a hat and a scarf.","cold"]] },
  medium: { w: [["thunder","grmenje","🌩️"],["lightning","strela","⚡"],["puddle","luža"],["ice","led","🧊"],["frost","slana, mraz"],["breeze","sapica"],["shower","ploha"],["temperature","temperatura","🌡️"],["degrees","stopinje"],["forecast","vremenska napoved"],["season","letni čas"],["spring","pomlad","🌸"],["summer","poletje","🏖️"],["autumn","jesen","🍂"],["winter","zima","⛄"]],
            s: [["The weather ___ says it will rain tomorrow.","forecast"],["The four ___ are spring, summer, autumn and winter.","seasons"],["We see ___ first and then hear thunder.","lightning"],["Water turns into ___ when it is very cold.","ice"],["It is 30 ___ today, so it is very hot.","degrees"]] },
  hard: { w: [["drought","suša"],["flood","poplava","🌊"],["hurricane","orkan"],["tornado","tornado","🌪️"],["heatwave","vročinski val"],["blizzard","snežni vihar"],["hail","toča"],["drizzle","pršenje"],["humid","vlažen"],["mild","blag"],["freezing","ledeno mrzel"],["overcast","oblačno"],["chilly","hladno"],["thaw","otopliti se"],["gale","močan veter"]],
          s: [["There has been no rain for months, so there is a ___.","drought"],["After the heavy rain there was a ___ in the village.","flood"],["It's not very cold, just ___: about 10 degrees in winter.","mild"],["Small hard pieces of ice falling from the sky are called ___.","hail"],["A very hot period of several days is a ___.","heatwave"]] } },

{ id: "jobs",
  easy: { w: [["nurse","medicinska sestra","👩‍⚕️"],["baker","pek","🧑‍🍳"],["driver","voznik","🚌"],["waiter","natakar","🍽️"],["artist","umetnik","🎨"]],
          s: [["A ___ helps the doctor in the hospital.","nurse"],["A ___ bakes bread.","baker"],["A ___ serves food in a restaurant.","waiter","waitress"],["A bus ___ drives people to work.","driver"],["A ___ paints pictures.","painter","artist"]] },
  medium: { w: [["vet","veterinar","🐕‍🦺"],["lawyer","odvetnik"],["engineer","inženir"],["electrician","električar","💡"],["plumber","vodovodar","🔧"],["builder","gradbenik","🏗️"],["hairdresser","frizer","💇"],["journalist","novinar"],["scientist","znanstvenik","🔬"],["shop assistant","prodajalec"],["secretary","tajnica"],["postman","poštar","📮"],["actor","igralec","🎭"],["photographer","fotograf","📷"],["tour guide","turistični vodnik"]],
            s: [["A ___ looks after sick animals.","vet"],["A ___ fixes broken pipes and taps.","plumber"],["A ___ cuts your hair.","hairdresser"],["A ___ brings letters to your house.","postman","postwoman","postie"],["A ___ works in a laboratory.","scientist"]] },
  hard: { w: [["architect","arhitekt"],["accountant","računovodja"],["surgeon","kirurg"],["pharmacist","lekarnar"],["translator","prevajalec"],["interpreter","tolmač"],["lifeguard","reševalec na plaži"],["judge","sodnik"],["social worker","socialni delavec"],["carpenter","mizar"],["fisherman","ribič","🎣"],["miner","rudar"],["sailor","mornar"],["customer","stranka"],["salary","plača"]],
          s: [["An ___ designs buildings.","architect"],["A ___ works in a chemist's and gives you medicine.","pharmacist","chemist"],["A ___ makes things from wood, like tables and doors.","carpenter"],["A ___ operates on patients in a hospital.","surgeon"],["The money you get every month for your work is your ___.","salary","wage","pay"]] } },

{ id: "hobbies",
  easy: { w: [["drawing","risanje","✏️"],["skating","drsanje","⛸️"],["skiing","smučanje","⛷️"],["fishing","ribolov","🎣"],["running","tek","🏃"]],
          s: [["In winter we go ___ in the mountains.","skiing"],["I use a pencil for ___.","drawing"],["My dad likes ___ at the lake: he catches fish.","fishing"],["I go ___ in the park every morning.","running","jogging"],["I put on my skates for ___.","skating","ice skating"]] },
  medium: { w: [["collecting stamps","zbiranje znamk"],["playing chess","igranje šaha","♟️"],["playing the guitar","igranje kitare","🎸"],["playing the piano","igranje klavirja","🎹"],["taking photos","fotografiranje","📷"],["gardening","vrtnarjenje","🌱"],["knitting","pletenje","🧶"],["sewing","šivanje"],["board games","namizne igre","🎲"],["horse riding","jahanje","🏇"],["rock climbing","plezanje","🧗"],["scouts","skavti"],["to join a club","včlaniti se v klub"],["free time","prosti čas"],["model making","izdelovanje modelov"]],
            s: [["I have a camera and I love ___ photos.","taking"],["Monopoly and Scrabble are ___ games.","board"],["My grandma likes ___ socks with wool.","knitting"],["In my ___ time I read comics.","free","spare"],["He plays ___ with a king, queen and pawns.","chess"]] },
  hard: { w: [["bird watching","opazovanje ptic"],["origami","origami"],["calligraphy","kaligrafija"],["pottery","lončarstvo"],["woodwork","obdelava lesa"],["archery","lokostrelstvo","🏹"],["fencing","sabljanje"],["gymnastics","gimnastika","🤸"],["surfing","deskanje na valovih","🏄"],["snowboarding","deskanje na snegu","🏂"],["jigsaw puzzle","sestavljanka","🧩"],["pastime","konjiček"],["to be keen on","biti navdušen nad"],["to be into","biti zagret za"],["to be fond of","imeti rad"]],
          s: [["Making a bowl from clay is called ___.","pottery"],["Shooting arrows at a target is ___.","archery"],["A ___ is a picture cut into many small pieces that you put together.","jigsaw","puzzle","jigsaw puzzle"],["Another word for hobby is ___.","pastime"],["I am really ___ on photography; I take pictures every day.","keen"]] } }
);
